### ISSUE TITLE
Make it work in windows?

### ISSUE THREAD

**Issue by AlanGeisse** [loathingKernel/Qutefan#2]
Hi, the most i have done is running batch files and some console programs. Can you guide me in what to do to make this run?

Already downloaded and extracted Qutefan-0.1.1 and NVAPI (R525 Developer).

I'm assuming I would need to compile something. VSC works for that?

Thanks in advance, sorry for my ignorance in this regard.

**Comment by loathingKernel** [comment]
You could try the binary from releases, but I am unsure if it will work since it hasn't been updated for some time so YMMV. It also needs a few modifications for the program to work on GFX cards with multiple fans. I have done those for Linux, so it is a matter of time for them to come to Windows.

Since I need it for myself too, I will be updating it in the next few days.
